[project]
name = "winfig-docs"
version = "1.0.0"
description = "Documentation for Winfig Project."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.22",
    "mkdocs-git-revision-date-localized-plugin>=1.4.7"
]
